# -*- sh -*-
# ~/.profile: executed by the command interpreter for login shells.

# if running bash
if [ -n "$z" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi


# Environment Variables
# Haskel Cabal
PATH=~/.cabal/bin:$PATH

if [ "$(uname -s)" = "Darwin" ]; then
	brewprefix=/opt/homebrew
	export PATH="$brewprefix/bin:$brewprefix/sbin:$PATH"
	export MANPATH="$brewprefix/share/man:$MANPATH"
	unset brewprefix
fi

