# -*- sh -*-
# ~/.profile: executed by the command interpreter for login shells.

# if running bash
if [ -n "$z" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi


# Environment Variables
# Haskel Cabal
# PATH=~/.cabal/bin:$PATH
