#!/bin/zsh
# -*- sh -*-
typeset -U path

if [ -d ~/bin ]; then
    path=(~/bin "$path[@]")
fi

if [ -d ~/.local/bin ]; then
    path=(~/.local/bin "$path[@]")
fi

if [ -d ~/.local/share/man ]; then
	manpath=(~/.local/share/man "$manpath[@]")
fi

export PATH MANPATH
export PATH=$PATH:/usr/local/go/bin

export EDITOR=vim
export VISUAL="emacsclient -a vim"
# export PYTHONSTARTUP=~/.pythonrc
export PAGER=less
export LESS=R
export CFLAGS="-Wall -pipe"

# export DEPOT_TOOLS_PATH='/home/shermpay/Code/OpenSource/depot_tools'
# export PATH="$DEPOT_TOOLS_PATH":"$PATH"

export MAILDIR=$HOME"/.mail"

# gtags
export GTAGSFORCECPP=1

# For Go
export GOPATH="$HOME/go"
path=("$GOPATH/bin" "$path[@]")

# For antlr
# export CLASSPATH=".:/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH"
# alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool'

# Source configuration required for shell tools(such as pyenv)
if [[ -f "$HOME/.shtools" ]]; then
    source "$HOME/.shtools"
fi

if [ -r ~/.zshenv.local ]; then
    source ~/.zshenv.local
fi
