#!/bin/zsh
# -*- sh -*-
typeset -U path manpath

if [ -d ~/bin ]; then
    path=(~/bin "$path[@]")
fi

if [ -d ~/.local/bin ]; then
    path=(~/.local/bin "$path[@]")
fi

if whence manpath >> /dev/null ; then
	manpath="$(manpath -q -g)"
fi

if [ -d ~/.local/share/man ]; then
	manpath=(~/.local/share/man "$manpath[@]")
fi

export PATH MANPATH
export PATH=$PATH:/usr/local/go/bin

export EDITOR='emacsclient -r -a vim'
export VISUAL="emacsclient -r -a vim"
# export PYTHONSTARTUP=~/.pythonrc
export PAGER=less
export LESS=R
export CFLAGS="-Wall -pipe"


if [[ "$(uname -s)" = "Darwin" ]]; then
  export CLICOLOR=1
fi

# export DEPOT_TOOLS_PATH='/home/shermpay/Code/OpenSource/depot_tools'
# export PATH="$DEPOT_TOOLS_PATH":"$PATH"

export MAILDIR=$HOME"/.mail"

# gtags
export GTAGSFORCECPP=1

# For Go
export GOPATH="$HOME/go"
path=("$GOPATH/bin" "$path[@]")

# For antlr
# export CLASSPATH=".:/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH"
# alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool'

# Source configuration required for shell tools(such as pyenv)
if [[ -f "$HOME/.shtools" ]]; then
    source "$HOME/.shtools"
fi

SSH_AUTH_SOCK_FILE="$HOME/.ssh/ssh_auth_sock"
if [ -n "$SSH_AUTH_SOCK" ]; then
  echo -n "$SSH_AUTH_SOCK" > "$SSH_AUTH_SOCK_FILE"
fi

get_ssh_auth_sock() {
  cat "$SSH_AUTH_SOCK_FILE"
}

update_ssh_auth_sock() {
  export SSH_AUTH_SOCK=$(get_ssh_auth_sock)
}

# LOCAL_ZSHLIB_DIR for sharing shell scripts
export LOCAL_ZSHLIB_DIR="$HOME/.local/lib/zsh"
setopt +o nomatch
for file in "$LOCAL_ZSHLIB_DIR/"*; do
  source "$file"
done
setopt -o nomatch

if [[ -r ~/.zshenv.local ]]; then
    source ~/.zshenv.local
fi
