# load shell libraries
mkdir -p "$INCLUDEDIR"
setopt +o nomatch
for i in "$HOME"/.local/include/*;
do
  source "$i"
done
echo ".zshrc: loaded libraries"
setopt -o nomatch

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]} l:|=* r:|=*' 'l:|=* r:|=*' 'r:|[._-]=** r:|=**'
zstyle :compinstall filename '/home/shermpay/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=80000
# End of lines configured by zsh-newuser-install

# Immediately append
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "

# Add timestamp to history
setopt EXTENDED_HISTORY

# Ignore duplicates when searching
setopt HIST_FIND_NO_DUPS
# The following will skip writing duplicates to the history file.
# setopt HIST_IGNORE_ALL_DUPS

# Dirstack
DIRSTACKFILE="$HOME/.cache/zsh/dirs"
mkdir -p "$HOME/.cache/zsh"
if [[ -f $DIRSTACKFILE ]] && [[ $#dirstack -eq 0 ]]; then
  dirstack=( ${(f)"$(< $DIRSTACKFILE)"} )
  [[ -d $dirstack[1] ]] && cd $dirstack[1]
fi
chpwd() {
  print -l $PWD ${(u)dirstack} >$DIRSTACKFILE
}

DIRSTACKSIZE=20

setopt autopushd pushdsilent pushdtohome

## Remove duplicate entries
setopt pushdignoredups

## This reverts the +/- operators.
setopt pushdminus

# enable color support
autoload -U colors && colors

# use Emacs mode
bindkey -e

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

# add handy aliases
if [ -x /usr/bin/dircolors -o "$(uname -s)" = "Darwin" ]; then
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Read from an alias file other aliases
if [[ -f ~/.zsh_aliases ]] ; then
    echo "reading .zsh_aliases ..."
    source ~/.zsh_aliases
fi
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


# PS1 Prompt
# userps1="\e[44m\[\e[1;36m\]\\u\[\e[m\]"
# dirps1="\e[40m\[\e[2;37m\][\\w]\[\e[m\]"
# cmd='{$(ls --color=always -t -w 80 | head -n 10 | xargs echo)}'
# prompt="\\nλ *> "
# export PS1="${debian_chroot:+($debian_chroot)}"$userps1$dirps1$cmd$prompt
# zsh Prompt
() {
  local user="%n"
  local host="%m"
  local newline=$'\n'
  local userps1="(${host})"
  local wd_prompt="[%3~]"
  local dirps1="%{$fg[cyan]%}${wd_prompt}%{$reset_color%}"
  local timestampps1="%{$fg[blue]%}<%D{%y-%m-%d %H:%M:%S}>%{$reset_color%}"
  local main_prompt="$ "

  PROMPT="${userps1}${dirps1}${timestampps1}${newline}${main_prompt}"
  RPROMPT=""
}

# For completion
fpath[1,0]=~/.zsh/completion/

# This way the completion script does not have to parse Bazel's options
# repeatedly.  The directory in cache-path must be created manually.
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# emacs vterm
if [[ "$INSIDE_EMACS" = 'vterm' ]] ; then
    echo "loading vterm.sh ..." 
    source "${INCLUDEDIR}/vterm.sh"
fi

autoload -Uz add-zsh-addhook
function cd_ls() {
    emulate -L zsh
    echo $(ls --color=auto | head -n 8)
}

 # Fix for TRAMP
 [[ $TERM = "dumb" ]] && unsetopt zle && PS1='$ '

if [ -r ~/.zshrc.local ]; then
	echo "loading .zshrc.local ..."
	source ~/.zshrc.local
fi


[ -f "/Users/shermanpay/.ghcup/env" ] && source "/Users/shermanpay/.ghcup/env" # ghcup-env